### ISSUE TITLE
default url of gfwlist

### ISSUE THREAD

**Issue by yujunz** [snachx/gfwlist2privoxy#1]
https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt is no longer valid. Consider using https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt instead

**Comment by snachx** [comment]
Thank you for your feedback. I haven't use this tool for a long time.
I will fix the problem soon. Also, pull request welcome.
Now you can download gfwlist.txt manually and specify it as the input file.
