### ISSUE TITLE
报错，怎么解决？ AttributeError: 'NoneType' object has no attribute 'splitlines' 

### ISSUE THREAD

**Issue by Zyx-A** [snachx/gfwlist2privoxy#4]
Python 2.7.15

Downloading gfwlist from https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
Traceback (most recent call last):
  File "/home/software/vpnPAC/gfwlist2privoxy/main.py", line 180, in <module>
    main()
  File "/home/software/vpnPAC/gfwlist2privoxy/main.py", line 172, in main
    domains = parse_gfwlist(content, user_rule)
  File "/home/software/vpnPAC/gfwlist2privoxy/main.py", line 70, in parse_gfwlist
    builtin_rules = pkgutil.get_data('gfwlist2privoxy', 'resources/builtin.txt').splitlines(False)
AttributeError: 'NoneType' object has no attribute 'splitlines'

**Comment by snachx** [comment]
这是没有获取到builtin.txt的原因，但是我测试是OK的。请问你是怎么运行的？

**Comment by Zyx-A** [comment]
已经解决了。
1、导入os模块，并获取当前python脚本所在路径

> import os
> gfwlist2privoxy = os.path.split(os.path.realpath(__file__))[0]

2、将
> builtin_rules = pkgutil.get_data('gfwlist2privoxy', 'resources/builtin.txt').splitlines(False)

替换成：

> builtin_rules = open(os.path.join(gfwlist2privoxy, 'resources/builtin.txt'), 'rb').read().splitlines(False)

3、另外两个函数reduce_domains 、generate_action 中，调用了pkgutil.get_data方法的地方，都如此修改。
