### ISSUE TITLE
有个问题想请教下

### ISSUE THREAD

**Issue by Zyx-A** [snachx/gfwlist2privoxy#5]
我想让终端里面的命令行程序也自动分流代理（TCP/UDP全协议支持，privoxy默认情况下只支持HTTP/HTTPS），但我目前使用的方案是 proxychains-ng + privoxy 。这个方案存在一个很蛋疼的问题：
1. 如果不开启 proxychains-ng 的 proxy DNS 功能，那么 proxychains-ng 会先将域名解析为IP后，再将信息传送给 privoxy ，但这样 privoxy 就得查询 IP 表，依据IP去选择，而不是依据域名去选择。
2. 如果开启 proxychains-ng 的 proxy DNS 功能，虽然部分域名能正确代理，但对于另外一部分域名 proxychains-ng 会返回一个224.0.0.1或其他设定的私网IP，这就特么蛋疼了。而这其中的机制一直没搞懂。

　　如果有其他方案，能达到上述要求，还望不吝赐教。如果没有现成的替代方案，有没有什么好的建议？

**Comment by snachx** [comment]
返回 224 的 IP 对你使用会造成什么问题吗？

proxy_dns 的机制就是这样

If the proxified app does a DNS request, we will return an IP from that range. On further accesses to this ip we will send the saved DNS name to the proxy.

**Comment by Zyx-A** [comment]
返回224的IP会造成我访问不到我实际想访问的主机，并提示诸如：301 Moved Permanently
或者，会造成诸如apt提示更新失败。而关闭proxy_dns或不走代理，就不会报错。
