### ISSUE TITLE
新的顶级域名 tld.txt 没更新，请同意合并

### ISSUE THREAD

**Issue by Zyx-A** [snachx/gfwlist2privoxy#6]
ICANN地址：https://newgtlds.icann.org/en/program-status/delegated-strings
新的 tld.txt 已经提交更新，麻烦与main合并下，谢谢。

另外，之前提交的对 main.py 等的更新，也请审核下，并酌情合并。

**Comment by snachx** [comment]
你可以提一下测试好的 pull request，谢谢。

**Comment by Zyx-A** [comment]
已经提交 pull request ，提交的就是我自己正在使用的版本。
